@host = http://{{hostname}}:{{port}}/api
@hostname = localhost
@port = 5173


### getUsers

GET /users HTTP/1.1
Accept: application/json
Content-Type: application/json
Host: {{host}}

### newSession

POST /users/sessions HTTP/1.1
Accept: application/json
Content-Type: application/json
Host: {{host}}

{
  "nidNo": "ggjkmh",
  "password": "password"
}

### getAllLabReports

GET /users/@me/reports HTTP/1.1
Accept: application/json
Authorization: Bearer {{newSession.response.body.$.data.accessToken}}
Content-Type: application/json
Host: {{host}}

### getLabReports

GET /users/@me/reports?testName=Total%20Cholesterol HTTP/1.1
Accept: application/json
Authorization: Bearer {{newSession.response.body.$.data.accessToken}}
Content-Type: application/json
Host: {{host}}

### newLabReports

POST /users/@me/reports HTTP/1.1
Accept: application/json
Authorization: Bearer {{newSession.response.body.$.data.accessToken}}
Content-Type: application/json
Host: {{host}}

{
  "sampleNo": "IF110391",
  "date": "2025-06-11 08:52 AM",
  "specimen": "Urine",
  "tests": [
    {
      "testName": "Colour",
      "result": "Light Yellow"
    },
    {
      "testName": "Transparency",
      "result": "Clear"
    },
    {
      "testName": "pH",
      "result": "5.0"
    },
    {
      "testName": "Sugar",
      "result": "Nil",
      "unit": "mg/dL",
      "referenceRange": "<50 = Normal,\r\n50 = Trace,\r\n100 = 1+,\r\n250 = 2+,\r\n500 = 3+,\r\n2000 = 4+"
    },
    {
      "testName": "Pus Cells",
      "result": "0",
      "unit": "/HPF"
    },
    {
      "testName": "RBCs",
      "result": "Nil",
      "unit": "/HPF"
    },
    {
      "testName": "Epithelial Cells",
      "result": "0",
      "unit": "/HPF"
    },
    {
      "testName": "Crystals",
      "result": "0",
      "unit": "/HPF"
    },
    {
      "testName": "Casts",
      "result": "0",
      "unit": "/HPF"
    },
    {
      "testName": "Protein",
      "result": "Nil",
      "unit": "mg/dL",
      "referenceRange": "<15=Normal,\r\n15=Trace,\r\n30=1+,\r\n100=2+,\r\n300=3+,\r\n1000=4+",
      "conversionFactor": "X 10 (mg/L)"
    }
  ]
}

### newLabReports

POST /users/@me/reports HTTP/1.1
Accept: application/json
Authorization: Bearer {{newSession.response.body.$.data.accessToken}}
Content-Type: application/json
Host: {{host}}

{
  "sampleNo": "IF110390",
  "date": "2025-06-11 08:52 AM",
  "specimen": "Stool",
  "tests": [
    {
      "testName": "H. Pylori Antigen Test ",
      "result": "Positive",
      "conversionFactor": "Immunochromatogra phy"
    }
  ]
}

### newLabReports

POST /users/@me/reports HTTP/1.1
Accept: application/json
Authorization: Bearer {{newSession.response.body.$.data.accessToken}}
Content-Type: application/json
Host: {{host}}

{
  "sampleNo": "asldkjasdasld",
  "date": "2025-05-14",
  "specimen": "Plasma",
  "tests": [
    {
      "testName": "Glucose F",
      "result": "98",
      "unit": "mg/dL",
      "referenceRange": "60 - 110",
      "method": "HEXOKINASE",
      "conversionFactor": "X 0.0555 (mmol/L)"
    },
    {
      "testName": "Urea",
      "result": "19",
      "unit": "mg/dL",
      "referenceRange": "13-43",
      "method": "UREASE- GLDH",
      "conversionFactor": "X 0.166 (mmol/L)"
    },
    {
      "testName": "Creatinine",
      "result": "1.3",
      "unit": "mg/dL",
      "referenceRange": "0.4-1.4",
      "method": "JAFFES KINETIC",
      "conversionFactor": "X 88.4(umol/L)"
    }
  ]
}
