@host = http://{{hostname}}:{{port}}/api
@hostname = localhost
@port = 5173


### getUsers

GET /users HTTP/1.1
Accept: application/json
Content-Type: application/json
Host: {{host}}

### newSession

POST /users/sessions HTTP/1.1
Accept: application/json
Content-Type: application/json
Host: {{host}}

{
  "nidNo": "aslkdjasdasd",
  "password": "password"
}

### getLabReports

GET /users/@me/reports
Accept: application/json
Authorization: Bearer {{newSession.response.body.$.data.accessToken}}
Content-Type: application/json
Host: {{host}}

### newLabReports

POST /users/@me/reports HTTP/1.1
Accept: application/json
Authorization: Bearer {{newSession.response.body.$.data.accessToken}}
Content-Type: application/json
Host: {{host}}

[
  {
    "testName": "Vitamin K",
    "result": "100",
    "date": "2081-04-12"
  }
]
