@host = http://{{hostname}}:{{port}}/api
@hostname = localhost
@port = 5173


### addFamilyAdmin

POST /users HTTP/1.1
Accept: application/json
Content-Type: application/json
Host: {{host}}

{
  "nidNo": "aslkdjasldkj",
  "nidImg": "aslkdjasldkj",
  "password": "password",
  "dob": "2003-11-05",
  "sex": "male",
  "name": "Anshu Gahire",
  "bloodtype": "A+",
  "role": "FAMILY_ADMIN"
}

### addMember

POST /users HTTP/1.1
Accept: application/json
Content-Type: application/json
Host: {{host}}

{
  "nidNo": "aslkdjasdasd",
  "nidImg": "aslkdjasldkj",
  "password": "password",
  "dob": "2003-11-05",
  "sex": "male",
  "name": "Anshu Gahire",
  "bloodtype": "A+",
  "role": "MEMBER",
  "familyAdmin": "684c65c53413251cb28bdfc8",
  "relationToFamilyAdmin": "MOTHER"
}

### getUsers

GET /users HTTP/1.1
Accept: application/json
Content-Type: application/json
Host: {{host}}

### newSession

POST /users/sessions HTTP/1.1
Accept: application/json
Content-Type: application/json
Host: {{host}}

{
  "nidNo": "aslkdjasldkj",
  "password": "password"
}
